version: '3.4'

services:
  frontend:
    container_name: 
    image: 
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5902:80
    stdin_open: true
    environment:
      - backendUrl=http://api
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - api
  api:
    image: 
    build:
      context: 
      dockerfile: Dockerfile
    ports:
      - '5900:80'